### ISSUE TITLE
hard link in script

### ISSUE THREAD

**Issue by leardilap** [meisonlikesicecream/optics-scan#1]
these two were changed in the SerA branch to $setAmpScript

https://github.com/meisonlikesicecream/optics-scan/blob/4420076544c94e6fd46f7c2c6f4dcc4514c601c3/Scans/Board04/Board04-BTScan-BER-Tx.tcl#L233

https://github.com/meisonlikesicecream/optics-scan/blob/4420076544c94e6fd46f7c2c6f4dcc4514c601c3/Scans/Board04/Board04-BTScan-BER-Tx.tcl#L236

**Comment by meisonlikesicecream** [comment]
Cheers, pushed a fix for it 👍
